### ISSUE TITLE
Might I Ask Why This Isn't On the Nexus?

### ISSUE THREAD

**Issue by Ragnarok345** [trench8891/PolyROM#13]
It would seem the obvious thing to me, especially since the original was there, and would make it easier to keep track of and discuss. Just curious.

**Comment by trench8891** [comment]
Because it's not really much more playable than what currently _is_ on Nexus, in its current state. The original mod author is involved and will update Nexus when it would be a qualitative improvement.

You certainly _may_ download the mod from here, but with a big major caveat that there current are no compatibility patches.
